// trip-front/src/components/architecture/EvaluationSystem.vue
<script setup lang="ts">
/**
 * 评估体系 (Evaluation System)
 *
 * 拓扑：fixtures → entry → runner → 4 modes → 13 evaluators → output → feedback loop
 * 闭环：output(negative) → feedback → fixtures（虚线）
 */
import { VueFlow, type Node, type Edge } from '@vue-flow/core'
import '@vue-flow/core/dist/style.css'
import ServiceNode from './nodes/ServiceNode.vue'
import GroupNode from './nodes/GroupNode.vue'
import CloudNode from './nodes/CloudNode.vue'
import DatabaseNode from './nodes/DatabaseNode.vue'

const nodeTypes = {
  service: ServiceNode,
  group: GroupNode,
  cloud: CloudNode,
  database: DatabaseNode,
}

const evaluators = [
  'must_contain_keywords',
  'must_not',
  'regex',
  'json_schema',
  'semantic_match',
  'tool_called',
  'latency',
  'token_count',
  'similarity',
  'contains_url',
  'language',
  'length',
  'cost',
]

const modes = ['mock', 'real', 'multi-sample', 'report']

const nodes: Node[] = [
  { id: 'fixtures', type: 'database', position: { x: 0, y: 20 }, data: { label: 'Fixtures (YAML)', sublabel: 'fixtures/**/*.yaml' } },
  { id: 'entry', type: 'service', position: { x: 220, y: 20 }, data: { label: 'CLI / API entry', sublabel: 'eval · evalApi', color: '#dae8fc' } },
  { id: 'runner', type: 'service', position: { x: 440, y: 20 }, data: { label: 'Runner', color: '#fff2cc' } },
  {
    id: 'modes',
    type: 'group',
    position: { x: 660, y: 0 },
    data: { label: '4 Modes', items: modes },
  },
  {
    id: 'evaluators',
    type: 'service',
    position: { x: 220, y: 200 },
    data: { label: `13 Evaluators`, sublabel: evaluators.slice(0, 4).join(' · ') + ' · ...', color: '#d5e8d4' },
  },
  { id: 'llm', type: 'cloud', position: { x: 0, y: 200 }, data: { label: 'LLM', sublabel: 'mock or real' } },
  { id: 'output', type: 'service', position: { x: 440, y: 200 }, data: { label: 'Output', sublabel: 'JSON · HTML · score', color: '#ffe6cc' } },
  { id: 'feedback', type: 'service', position: { x: 660, y: 200 }, data: { label: 'Feedback Loop', sublabel: 'fixtureConverter', color: '#e1d5e7' } },
]

const labelStyle = { fontSize: '10px', fill: '#333' }

const edges: Edge[] = [
  { id: 'e1', source: 'fixtures', target: 'entry', style: { stroke: '#1976d2', strokeWidth: 2 } },
  { id: 'e2', source: 'entry', target: 'runner', style: { stroke: '#1976d2', strokeWidth: 2 } },
  { id: 'e3', source: 'runner', target: 'modes', style: { stroke: '#1976d2', strokeWidth: 2 } },
  { id: 'e4', source: 'modes', target: 'evaluators', style: { stroke: '#82b366', strokeWidth: 2 } },
  { id: 'e5', source: 'evaluators', target: 'llm', label: 'invoke', labelStyle, style: { stroke: '#999', strokeWidth: 1.5, strokeDasharray: '4 4' } },
  { id: 'e6', source: 'evaluators', target: 'output', style: { stroke: '#82b366', strokeWidth: 2 } },
  { id: 'e7', source: 'output', target: 'feedback', label: 'negative', labelStyle, style: { stroke: '#d79b00', strokeWidth: 2 } },
  { id: 'e8', source: 'feedback', target: 'fixtures', label: 'append new fixture', labelStyle, style: { stroke: '#9673a6', strokeWidth: 2, strokeDasharray: '4 4' } },
]
</script>

<template>
  <div class="diagram-canvas">
    <VueFlow
      :nodes="nodes"
      :edges="edges"
      :node-types="nodeTypes"
      :default-viewport="{ x: 0, y: 0, zoom: 0.9 }"
      fit-view-on-init
      :nodes-draggable="false"
    />
  </div>
</template>

<style scoped>
.diagram-canvas {
  width: 100%;
  height: 100%;
  background: #fafafa;
}
</style>

<style>
.vue-flow {
  background: #fafafa;
}
</style>

// docs/architecture-comparison/react-flow/EvaluationSystem.tsx
import { ReactFlow, Handle, Position, type Node, type Edge, type NodeProps } from '@xyflow/react'
import '@xyflow/react/dist/style.css'

// ─── Custom Node: Group (2x2 grid of modes) ───────────────────────────────────
function GroupNode({ data, selected }: NodeProps) {
  const cells = [
    { label: 'mock', color: '#d5e8d4', border: '#82b366' },
    { label: 'real', color: '#dae8fc', border: '#6c8ebf' },
    { label: 'multi-sample', color: '#e1d5e7', border: '#9673a6' },
    { label: 'report', color: '#ffe6cc', border: '#d79b00' },
  ]
  return (
    <div style={{ position: 'relative' }}>
      <Handle type="target" position={Position.Top} />
      <div
        style={{
          background: '#f5f5f5',
          border: `${selected ? 3 : 2}px solid #333`,
          borderRadius: 8,
          padding: 8,
          width: 220,
        }}
      >
        <div
          style={{
            fontSize: 11,
            fontWeight: 700,
            color: '#333',
            marginBottom: 6,
            textAlign: 'center',
            letterSpacing: 0.5,
          }}
        >
          4 MODES
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 }}>
          {cells.map((c) => (
            <div
              key={c.label}
              style={{
                background: c.color,
                border: `1.5px solid ${c.border}`,
                borderRadius: 4,
                padding: '8px 4px',
                textAlign: 'center',
                fontSize: 11,
                fontWeight: 600,
                color: '#333',
              }}
            >
              {c.label}
            </div>
          ))}
        </div>
      </div>
      <Handle type="source" position={Position.Bottom} />
    </div>
  )
}

// ─── Custom Node: Default (rounded rectangle) ─────────────────────────────────
function ProcessNode({ data, selected }: NodeProps) {
  const label = (data as { label: string }).label
  return (
    <div style={{ position: 'relative' }}>
      <Handle type="target" position={Position.Left} />
      <Handle type="target" position={Position.Top} />
      <div
        style={{
          background: '#dae8fc',
          border: `${selected ? 3 : 2}px solid #6c8ebf`,
          borderRadius: 8,
          padding: '10px 14px',
          minWidth: 130,
          maxWidth: 220,
          textAlign: 'center',
          fontWeight: 600,
          fontSize: 12,
          color: '#1a3a6c',
          whiteSpace: 'pre-line',
        }}
      >
        {label}
      </div>
      <Handle type="source" position={Position.Right} />
      <Handle type="source" position={Position.Bottom} />
    </div>
  )
}

const nodeTypes = { group: GroupNode, process: ProcessNode }

// ─── Graph (TB layout) ────────────────────────────────────────────────────────
const nodes: Node[] = [
  {
    id: 'fx',
    type: 'process',
    position: { x: 260, y: 0 },
    data: { label: 'Fixtures\nfixtures/*.yaml +\nfixtures/generated/*.yaml' },
  },
  {
    id: 'en',
    type: 'process',
    position: { x: 260, y: 140 },
    data: { label: 'CLI / API entry\n(eval / evalApi)' },
  },
  {
    id: 'run',
    type: 'process',
    position: { x: 260, y: 280 },
    data: { label: 'Runner' },
  },
  {
    id: 'md',
    type: 'group',
    position: { x: 200, y: 420 },
    data: {},
  },
  {
    id: 'ev',
    type: 'process',
    position: { x: 260, y: 620 },
    data: { label: '13 Evaluators\nmust_contain_keywords · must_not ·\nregex · json_schema · ...' },
  },
  {
    id: 'llm',
    type: 'process',
    position: { x: 0, y: 620 },
    data: { label: 'LLM\n(mock or real)' },
  },
  {
    id: 'out',
    type: 'process',
    position: { x: 260, y: 800 },
    data: { label: 'Output\nJSON report · HTML report · score' },
  },
  {
    id: 'fb',
    type: 'process',
    position: { x: 260, y: 960 },
    data: { label: 'Feedback Loop\nnegative feedback →\nfixtureConverter → new YAML' },
  },
]

const edges: Edge[] = [
  { id: 'fx-en', source: 'fx', target: 'en', style: { stroke: '#6c8ebf', strokeWidth: 2 } },
  { id: 'en-run', source: 'en', target: 'run', style: { stroke: '#6c8ebf', strokeWidth: 2 } },
  { id: 'run-md', source: 'run', target: 'md', style: { stroke: '#6c8ebf', strokeWidth: 2 } },
  { id: 'md-ev', source: 'md', target: 'ev', style: { stroke: '#6c8ebf', strokeWidth: 2 } },
  { id: 'ev-llm', source: 'ev', target: 'llm', label: '↔ invoke', style: { stroke: '#9673a6', strokeWidth: 2 }, animated: true },
  { id: 'ev-out', source: 'ev', target: 'out', style: { stroke: '#6c8ebf', strokeWidth: 2 } },
  { id: 'out-fb', source: 'out', target: 'fb', label: 'negative', style: { stroke: '#d62728', strokeWidth: 2 } },
  { id: 'fb-fx', source: 'fb', target: 'fx', label: 'append', style: { stroke: '#82b366', strokeWidth: 2 } },
]

export function EvaluationSystem() {
  return (
    <div style={{ width: '100%', height: 1100 }}>
      <ReactFlow
        nodes={nodes}
        edges={edges}
        nodeTypes={nodeTypes}
        fitView
        proOptions={{ hideAttribution: true }}
      />
    </div>
  )
}

export default EvaluationSystem
