// docs/architecture-comparison/react-flow/ContextDataFlow.tsx
import { ReactFlow, Handle, Position, type Node, type Edge, type NodeProps } from '@xyflow/react'
import '@xyflow/react/dist/style.css'

// ─── Custom Node: Decision (diamond) ──────────────────────────────────────────
function DecisionNode({ data, selected }: NodeProps) {
  const label = (data as { label: string }).label
  return (
    <div style={{ position: 'relative' }}>
      <Handle type="target" position={Position.Left} />
      <svg width="180" height="100" viewBox="0 0 180 100">
        <polygon
          points="90,5 175,50 90,95 5,50"
          fill="#fff2cc"
          stroke="#d6b656"
          strokeWidth={selected ? 3 : 2}
        />
        <text x="90" y="46" textAnchor="middle" fontSize="11" fontWeight="600" fill="#5d4500">
          {label}
        </text>
        <text x="90" y="60" textAnchor="middle" fontSize="9" fill="#7a5a00">
          (decision)
        </text>
      </svg>
      <Handle type="source" position={Position.Right} />
    </div>
  )
}

// ─── Custom Node: Default (rounded rectangle) ─────────────────────────────────
function ProcessNode({ data, selected }: NodeProps) {
  const label = (data as { label: string }).label
  return (
    <div style={{ position: 'relative' }}>
      <Handle type="target" position={Position.Left} />
      <div
        style={{
          background: '#dae8fc',
          border: `${selected ? 3 : 2}px solid #6c8ebf`,
          borderRadius: 8,
          padding: '10px 14px',
          minWidth: 130,
          textAlign: 'center',
          fontWeight: 600,
          fontSize: 12,
          color: '#1a3a6c',
          whiteSpace: 'pre-line',
        }}
      >
        {label}
      </div>
      <Handle type="source" position={Position.Right} />
    </div>
  )
}

const nodeTypes = { decision: DecisionNode, process: ProcessNode }

// ─── Graph (LR layout) ───────────────────────────────────────────────────────
const nodes: Node[] = [
  { id: 'um', type: 'process', position: { x: 0, y: 180 }, data: { label: 'User\nmessage' } },
  { id: 'hist', type: 'process', position: { x: 220, y: 180 }, data: { label: 'Message history\nMySQL' } },
  { id: 'tc', type: 'process', position: { x: 440, y: 180 }, data: { label: 'Token counter\ncurrent usage' } },
  { id: 'budget', type: 'decision', position: { x: 660, y: 180 }, data: { label: 'Token budget\nHISTORY_MAX_TOKENS=8000' } },
  { id: 'keep', type: 'process', position: { x: 920, y: 40 }, data: { label: 'Keep all\nmessages' } },
  { id: 'summ', type: 'process', position: { x: 920, y: 180 }, data: { label: 'Summarize\nold msgs' } },
  { id: 'cmp', type: 'process', position: { x: 920, y: 320 }, data: { label: 'Compressor\ncompressConversation' } },
  { id: 'sc', type: 'process', position: { x: 1160, y: 180 }, data: { label: 'Summary cache\nin-memory' } },
  { id: 'llm', type: 'process', position: { x: 1400, y: 180 }, data: { label: 'LLM call\ncompressed context' } },
]

const edges: Edge[] = [
  { id: 'um-hist', source: 'um', target: 'hist', style: { stroke: '#6c8ebf', strokeWidth: 2 } },
  { id: 'hist-tc', source: 'hist', target: 'tc', style: { stroke: '#6c8ebf', strokeWidth: 2 } },
  { id: 'tc-budget', source: 'tc', target: 'budget', style: { stroke: '#6c8ebf', strokeWidth: 2 } },
  { id: 'budget-keep', source: 'budget', target: 'keep', label: 'within', style: { stroke: '#82b366', strokeWidth: 2 } },
  { id: 'budget-summ', source: 'budget', target: 'summ', label: 'approaching', style: { stroke: '#d6b656', strokeWidth: 2 } },
  { id: 'budget-cmp', source: 'budget', target: 'cmp', label: 'exceeded', style: { stroke: '#d62728', strokeWidth: 2 } },
  { id: 'summ-sc', source: 'summ', target: 'sc', style: { stroke: '#d6b656', strokeWidth: 2 } },
  { id: 'sc-cmp', source: 'sc', target: 'cmp', style: { stroke: '#d6b656', strokeWidth: 2 } },
  { id: 'cmp-llm', source: 'cmp', target: 'llm', style: { stroke: '#9673a6', strokeWidth: 2 } },
  { id: 'keep-llm', source: 'keep', target: 'llm', style: { stroke: '#82b366', strokeWidth: 2 } },
]

export function ContextDataFlow() {
  return (
    <div style={{ width: '100%', height: 500 }}>
      <ReactFlow
        nodes={nodes}
        edges={edges}
        nodeTypes={nodeTypes}
        fitView
        proOptions={{ hideAttribution: true }}
      />
    </div>
  )
}

export default ContextDataFlow

// trip-front/src/components/architecture/ContextDataFlow.vue
<script setup lang="ts">
/**
 * 上下文管理数据流 (Context Management Data Flow)
 *
 * 横向流程：message → history → counter → budget(决策) → 三分支 → compressor → LLM
 * 三分支：within（绿）、near（黄）、over（红）
 */
import { VueFlow, type Node, type Edge } from '@vue-flow/core'
import '@vue-flow/core/dist/style.css'
import ServiceNode from './nodes/ServiceNode.vue'
import DatabaseNode from './nodes/DatabaseNode.vue'
import DecisionNode from './nodes/DecisionNode.vue'
import CloudNode from './nodes/CloudNode.vue'

const nodeTypes = {
  service: ServiceNode,
  database: DatabaseNode,
  decision: DecisionNode,
  cloud: CloudNode,
}

const nodes: Node[] = [
  { id: 'msg', type: 'service', position: { x: 0, y: 100 }, data: { label: 'User Message', color: '#dae8fc' } },
  { id: 'history', type: 'database', position: { x: 180, y: 100 }, data: { label: 'Message History', sublabel: 'MySQL' } },
  { id: 'counter', type: 'service', position: { x: 360, y: 100 }, data: { label: 'Token Counter', sublabel: 'current usage', color: '#fff2cc' } },
  { id: 'budget', type: 'decision', position: { x: 540, y: 80 }, data: { label: 'Token Budget?', sublabel: 'HISTORY_MAX=8000' } },
  { id: 'keep', type: 'service', position: { x: 740, y: -20 }, data: { label: 'Keep All', sublabel: 'within budget', color: '#d5e8d4' } },
  { id: 'summarize', type: 'service', position: { x: 740, y: 100 }, data: { label: 'Summarize Old', sublabel: 'approaching limit', color: '#ffe6cc' } },
  { id: 'compress', type: 'service', position: { x: 740, y: 220 }, data: { label: 'Compress Path', sublabel: 'exceeded', color: '#f8cecc' } },
  { id: 'compressor', type: 'service', position: { x: 940, y: 100 }, data: { label: 'compressConversation', color: '#fff2cc' } },
  { id: 'summary-cache', type: 'database', position: { x: 940, y: 240 }, data: { label: 'Summary Cache', sublabel: 'in-memory' } },
  { id: 'llm-call', type: 'cloud', position: { x: 1140, y: 100 }, data: { label: 'LLM Call', sublabel: 'compressed ctx' } },
]

const labelStyle = { fontSize: '10px', fill: '#333' }

const edges: Edge[] = [
  { id: 'e1', source: 'msg', target: 'history', style: { stroke: '#999', strokeWidth: 1.5 } },
  { id: 'e2', source: 'history', target: 'counter', style: { stroke: '#999', strokeWidth: 1.5 } },
  { id: 'e3', source: 'counter', target: 'budget', style: { stroke: '#999', strokeWidth: 1.5 } },
  { id: 'e4', source: 'budget', sourceHandle: 'yes', target: 'keep', label: 'within', labelStyle, style: { stroke: '#82b366', strokeWidth: 2 } },
  { id: 'e5', source: 'budget', target: 'summarize', label: 'near', labelStyle, style: { stroke: '#d6b656', strokeWidth: 2 } },
  { id: 'e6', source: 'budget', sourceHandle: 'no', target: 'compress', label: 'over', labelStyle, style: { stroke: '#b85450', strokeWidth: 2 } },
  { id: 'e7', source: 'keep', target: 'compressor', style: { stroke: '#82b366', strokeDasharray: '4 4' } },
  { id: 'e8', source: 'summarize', target: 'compressor', style: { stroke: '#d6b656', strokeWidth: 2 } },
  { id: 'e9', source: 'compress', target: 'compressor', style: { stroke: '#b85450', strokeWidth: 2 } },
  { id: 'e10', source: 'compressor', target: 'summary-cache', style: { stroke: '#999', strokeDasharray: '4 4' } },
  { id: 'e11', source: 'compressor', target: 'llm-call', style: { stroke: '#1976d2', strokeWidth: 2 }, animated: true },
]
</script>

<template>
  <div class="diagram-canvas">
    <VueFlow
      :nodes="nodes"
      :edges="edges"
      :node-types="nodeTypes"
      :default-viewport="{ x: 0, y: 0, zoom: 0.8 }"
      fit-view-on-init
      :nodes-draggable="false"
    />
  </div>
</template>

<style scoped>
.diagram-canvas {
  width: 100%;
  height: 100%;
  background: #fafafa;
}
</style>

<style>
.vue-flow {
  background: #fafafa;
}
</style>
